security:
  providers:
    jwt:
      lexik_jwt:
        class: App\Entity\User
  encoders:
    App\Entity\User:
      algorithm: auto
  firewalls:
    login:
      pattern:  ^/api/v1/login
      stateless: true
      anonymous: true
      json_login:
        check_path:      /api/v1/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern:   ^/api/v1
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
  access_control:
    - { path: ^/api/v1/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/callback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1,          roles: IS_AUTHENTICATED_FULLY }
